support --vendor-data
bzr-revno: 281.1.4

diff --git a/bin/cloud-localds b/bin/cloud-localds
--- a/bin/cloud-localds
+++ b/bin/cloud-localds
@@ -29,6 +29,7 @@ Usage: ${0##*/} [ options ] output user-data [meta-data]
      -m | --dsmode      M    add 'dsmode' ('local' or 'net') to the metadata
                              default in cloud-init is 'net', meaning network is
                              required.
+     -V | --vendor-data F    vendor-data file
      -v | --verbose          increase verbosity
 
    Note, --dsmode, --hostname, and --interfaces are incompatible
@@ -59,9 +60,9 @@ debug() {
 	error "${@}"
 }
 
-short_opts="hH:i:d:f:m:N:o:v"
+short_opts="hH:i:d:f:m:N:o:V:v"
 long_opts="disk-format:,dsmode:,filesystem:,help,hostname:,interfaces:,"
-long_opts="${long_opts}network-config:,output:,verbose"
+long_opts="${long_opts}network-config:,output:,vendor-data:,verbose"
 getopt_out=$(getopt --name "${0##*/}" \
 	--options "${short_opts}" --long "${long_opts}" -- "$@") &&
 	eval set -- "${getopt_out}" ||
@@ -71,6 +72,7 @@ getopt_out=$(getopt --name "${0##*/}" \
 output=""
 userdata=""
 metadata=""
+vendordata=""
 filesystem=""
 diskformat=$DEF_DISK_FORMAT
 interfaces=_unset
@@ -90,6 +92,7 @@ while [ $# -ne 0 ]; do
 		-N|--network-config) netcfg=$next; shift;;
 		-m|--dsmode) dsmode=$next; shift;;
 		-v|--verbose) VERBOSITY=$((${VERBOSITY}+1));;
+		-V|--vendor-data) vendordata="$next";;
 		--) shift; break;;
 	esac
 	shift;
@@ -159,6 +162,12 @@ if [ -n "$netcfg" ]; then
 	files[${#files[@]}]="$TEMP_D/$ncname"
 fi
 
+if [ -n "$vendordata" ]; then
+	cp "$vendordata" "${TEMP_D}/vendor-data" ||
+		fail "failed to copy vendor data"
+	files[${#files[@]}]="$TEMP_D/vendor-data"
+fi
+
 files_rel=( )
 for f in "${files[@]}"; do
 	files_rel[${#files_rel[@]}]="${f#${TEMP_D}/}"
@@ -171,10 +180,13 @@ else
 fi
 
 ## alternatively, create a vfat filesystem with same files
-img="$TEMP_D/seed.img"
-truncate --size 100K "$img" || fail "failed truncate image"
-
+img="$TEMP_D/seed-data"
 tar_opts=( --owner=root --group=root )
+
+case "$filesytem" in
+	iso9660|iso|vfat)
+		truncate --size 100K "$img" || fail "failed truncate image";;
+esac
 
 case "$filesystem" in
 	tar)
@@ -201,6 +213,7 @@ case "$filesystem" in
 			{ cat "$TEMP_D/err" 1>&2; fail "failed to genisoimage"; }
 		;;
 	vfat)
+		truncate --size 100K "$img" || fail "failed truncate image"
 		mkfs.vfat -n cidata "$img" || fail "failed mkfs.vfat"
 		mcopy -oi "$img" "${files[@]}" :: ||
 			fail "failed to copy user-data, meta-data to img"
