cloud-publish-image: improve "is it a loader?" check
Improve the "is this a loader kernel/ramdisk" check.
 * allow kernel/ramdisk = "none" (means "no kernel/ramdisk")
 * require kernel and ramdisk given to allow the loader mismatch
 * generally check and raise error if there is a mismatch.

bzr-revno: 162

diff --git a/bin/cloud-publish-image b/bin/cloud-publish-image
--- a/bin/cloud-publish-image
+++ b/bin/cloud-publish-image
@@ -276,21 +276,30 @@ else
 fi
 trap cleanup EXIT
 
-if [ -n "$kernel" ]; then
-	${EC2PRE}describe-images > "${TMPD}/kernel.info" ||
+if [ -n "$kernel" -a "$kernel" != "none" ]; then
+	aki_arch=""; ari_arch="";
+	# if kernel is given, check that its arch matches the register arch
+	aki_arch=""; ari_arch="";
+	${EC2PRE}describe-images "$kernel" "$ramdisk" > "${TMPD}/kernel.info" ||
 		fail "failed to describe kernel ${kernel}"
-	aki_arch=$(awk '-F\t' '$1 == "IMAGE" && $2 == eki { print $8 }' \
-		"eki=$kernel" "$TMPD/kernel.info") && [ -n "$aki_arch" ] ||
+	aki_arch=$(awk '-F\t' '$1 == "IMAGE" && $2 == id { print $8 }' \
+		"id=$kernel" "$TMPD/kernel.info") && [ -n "$aki_arch" ] ||
 		fail "failed to get arch of $kernel"
-fi
+	if [ -n "$ramdisk" -a "$ramdisk" != "none" ]; then
+		ari_arch=$(awk '-F\t' '$1 == "IMAGE" && $2 == id { print $8 }' \
+			"id=$ramdisk" "$TMPD/kernel.info") && [ -n "$ari_arch" ] ||
+			fail "failed to get arch of $ramdisk"
+	fi
 
-if [ "$arch" = "i386" -a "$aki_arch" = "x86_64" ]; then
-	# if arch = i386 and kernel is x86_64, assume this is a
-	# loader kernel and let it be (x86_64 kernel loading i386 instance)
-	error "WARNING: assuming loader kernel ($kernel arch=$aki_arch, arch=i386)"
-	arch="x86_64"
-elif [ "$arch" != "$aki_arch" -a -n "$aki_arch" ]; then
-	fail "kernel $kernel is arch $aki_arch, does not match arch $arch"
+	# if kernel and ramdisk are given, and arch=i386 kernel/ramdisk=x86_64,
+	# then assume loader kernel.
+	case "$arch:$aki_arch:$ari_arch" in
+		$arch:$arch:$arch|$arch:$arch:) : ;;
+		i386:x86_64:x86_64)
+			error "WARNING: assuming loader kernel ($kernel/$ramdisk arch=$aki_arch, provided arch=$arch)"
+			arch="x86_64";;
+		*) fail "arch $arch != kernel/ramdisk arch [$aki_arch/$ari_arch]";;
+	esac
 fi
 
 save_dir="${wdir}"
