Disks can be referred to via symlink aliases, such as the ones in /dev/disk/by-id and /dev/disk/by-path.  These alias paths can have different partition naming behavior than the un-aliased path.  For example, both of the above aliases add -partX to the name for partition X, rather than just X.  Previously this would cause growpart to fail with the error:
    failed to get start and end for ${dpart} in ${DISK}

Because the awk expression would not match the partition path.  This
commit fixes the error by resolving symlink device paths before use.

LP: #1744406
bzr-revno: 322.2.1

diff --git a/bin/growpart b/bin/growpart
--- a/bin/growpart
+++ b/bin/growpart
@@ -767,6 +767,15 @@ get_sfdisk_version || fail
 
 [ -e "${DISK}" ] || fail "${DISK}: does not exist"
 
+# If $DISK is a symlink, resolve it.
+# This avoids problems due to varying partition device name formats
+# (e.g. "1" for /dev/sda vs "-part1" for /dev/disk/by-id/name)
+if [ -L "${DISK}" ] ; then
+	real_disk=$(readlink -f "${DISK}") || fail "unable to resolve ${DISK}"
+	debug 1 "${DISK} resolved to ${real_disk}"
+	DISK=${real_disk}
+fi
+
 [ "${PART#*[!0-9]}" = "${PART}" ] || fail "partition-number must be a number"
 
 verify_ptupdate "$pt_update" || fail
