growpart: ignore sfdisk failure in 2.28.1 when due to reread failing
version 2.28.1 exits failure when kernel re-read of partition table
fails.  That is expected behavior in growpart, and addressed elsewhere.

See util-linux git commit 78e7f78896f2c for list of exit values when.

LP: #1619285
bzr-revno: 299

diff --git a/bin/growpart b/bin/growpart
--- a/bin/growpart
+++ b/bin/growpart
@@ -164,9 +164,16 @@ sfdisk_worked_but_blkrrpart_failed() {
 	# exit code found was just 1, but dont insist on that
 	#[ $ret -eq 1 ] || return 1
 	# Successfully wrote the new partition table
-	grep -qi "Success.* wrote.* new.* partition" "$output" &&
+	if grep -qi "Success.* wrote.* new.* partition" "$output"; then
 		grep -qi "BLKRRPART: Device or resource busy" "$output"
-	return
+		return
+	# The partition table has been altered.
+	elif grep -qi "The.* part.* table.* has.* been.* altered" "$output"; then
+		# Re-reading the partition table failed
+		grep -qi "Re-reading.* partition.* table.* failed" "$output"
+		return
+	fi
+	return $ret
 }
 
 get_sfdisk_version() {
@@ -337,7 +344,10 @@ resize_sfdisk() {
 	[ $ret -eq 0 ] || RESTORE_FUNC="${restore_func}"
 
 	if [ $ret -eq 0 ]; then
-		:
+		debug 1 "resize of ${DISK} returned 0."
+		if [ $VERBOSITY -gt 2 ]; then
+			sed 's,^,| ,' "${change_out}" 1>&2
+		fi
 	elif $PT_UPDATE &&
 		sfdisk_worked_but_blkrrpart_failed "$ret" "${change_out}"; then
 		# if the command failed, but it looks like only because
