Growpart: add support for resizing an lvm pv after growing the partition.
If lvm is available and lvm knows that the partition is part of a PV,
then resize tell lvm to grow the PV.

LP: #1799953

diff --git a/bin/growpart b/bin/growpart
--- a/bin/growpart
+++ b/bin/growpart
@@ -829,6 +829,39 @@ get_resizer() {
 	return 0
 }
 
+maybe_lvm_resize() {
+	local disk="$1" part="$2" partpath="" ret="" out="" wouldrun=""
+	[ "$DRY_RUN" -ne 0 ] && wouldrun="would-run"
+
+	has_cmd lvm || {
+		debug 2 "No lvm command, cannot attempt lvm resize of disk '$disk' part '$part'"
+		return 0
+	}
+	get_diskpart_path "$1" "$2" || {
+		error "could not determine partition path for disk '$DISK' part '$part'"
+		return 1
+	}
+	partpath="$_RET"
+
+	# can't use rq or rqe here because of "not an lvm" exit code 5.
+	set -- lvm pvs --nolocking --readonly -o pvname "$partpath"
+	debug 2 "executing: $*"
+	out=$("$@" 2>&1)
+	ret=$?
+	case "$ret" in
+		5) debug 1 "$partpath is not an lvm pv"; return 0;;
+		0) :;;
+		*) error "failed to execute [$ret] '$*'"
+			error "$out"
+			return 1;;
+	esac
+	rq lvm_resize $wouldrun lvm pvresize "$partpath" || {
+		error "Failed to resize lvm pv $partpath"
+		return 1
+	}
+	return 0
+}
+
 pt_update="auto"
 resizer=${GROWPART_RESIZER:-"auto"}
 while [ $# -ne 0 ]; do
@@ -927,6 +960,10 @@ debug 1 "resizing $PART on $DISK using $resizer"
 ret=$?
 
 unlock_disk_and_settle $DISK
+
+if [ "$RESIZE_RESULT" = "CHANGED" -o "$RESIZE_RESULT" = "CHANGE" ]; then
+	maybe_lvm_resize "$DISK" "$PART" || fail "lvm resize failed."
+fi
 
 exit $ret
 
