growpart: more coding style changes (no functional changes)
* limit line width to 80 chars
* fix indentation
* one command per line
* fix a spelling error
* add a debug output

bzr-revno: 208.2.6

diff --git a/bin/growpart b/bin/growpart
--- a/bin/growpart
+++ b/bin/growpart
@@ -45,11 +45,14 @@ changed() {
 
 cleanup() {
 	if [ -n "${RESTORE_FROM}" ]; then
-		error "***** WARNING: Resize failed, attempting to revert ******"
-		if sfdisk --no-reread "${DISK}" ${CHS} -I "${RESTORE_FROM}"; then
+		error "***** WARNING: Resize failed, attempting to revert" \
+			"******"
+		if sfdisk --no-reread "${DISK}" ${CHS} -I "${RESTORE_FROM}"; \
+		then
 			error "***** Appears to have gone OK ****"
 		else
-			error "***** FAILED! or original partition table looked like: ****"
+			error "***** FAILED! or original partition table" \
+				"looked like: ****"
 			cat "${RESTORE_HUMAN}" 1>&2
 		fi
 	fi
@@ -65,9 +68,10 @@ debug() {
 
 mktemp_d() {
 	# just a mktemp -d that doens't need mktemp if its not there.
-	_RET=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX" 2>/dev/null) && return
-	_RET=$(umask 077 && t="${TMPDIR:-/tmp}/${0##*/}.$$" && mkdir "${t}" &&
-		echo "${t}")
+	_RET=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX" 2>/dev/null) && \
+		return
+	_RET=$(umask 077 && t="${TMPDIR:-/tmp}/${0##*/}.$$" && \
+		mkdir "${t}" &&	echo "${t}")
 	return
 }
 
@@ -76,7 +80,7 @@ Usage() {
 ${0##*/} disk partition
    rewrite partition table so that partition takes up all the space it can
    options:
-    -h | --help      print Usage an exit
+    -h | --help      print Usage and exit
          --fudge F   if part could be resized, but change would be
                      less than 'F', do not resize (default: ${FUDGE})
     -N | --dry-run   only report what would be done, show new 'sfdisk -d'
@@ -99,30 +103,47 @@ fudge=${FUDGE}
 disk=""
 part=""
 while [ $# -ne 0 ]; do
-	cur=${1}; next=${2};
+	cur=${1}
+	next=${2}
 	case "$cur" in
-		-h|--help) Usage; exit 0;;
-		   --fudge) fudge=${next}; shift;;
-		-N|--dry-run) dry_run=1;;
-		-v|--verbose) VERBOSITY=$(($VERBOSITY+1));;
-		--) shift; break;;
-		-*) fail "unknown option ${cur}";;
-		*) 
+		-h|--help)
+			Usage
+			exit 0
+			;;
+		--fudge)
+			fudge=${next}
+			shift
+			;;
+		-N|--dry-run)
+			dry_run=1
+			;;
+		-v|--verbose)
+			VERBOSITY=$(($VERBOSITY+1))
+			;;
+		--)
+			shift
+			break
+			;;
+		-*)
+			fail "unknown option ${cur}"
+			;;
+		*)
 			if [ -z "${disk}" ]; then
-				disk=${cur};
+				disk=${cur}
 			else
-				[ -z "${part}" ] || fail "confused by arg ${cur}"
-				part=${cur};
+				[ -z "${part}" ] || \
+					fail "confused by arg ${cur}"
+				part=${cur}
 			fi
 			;;
 	esac
-	shift;
+	shift
 done
 
 [ -n "${disk}" ] || bad_Usage "must supply disk and partition-number"
 [ -n "${part}" ] || bad_Usage "must supply partition-number"
 
-[ -e "${disk}" ] || { fail "${disk}: does not exist"; }
+[ -e "${disk}" ] || fail "${disk}: does not exist"
 
 [ "${part#*[!0-9]}" = "${part}" ] || fail "partition-number must be a number"
 
@@ -140,22 +161,24 @@ RESTORE_HUMAN="${TEMP_D}/recovery"
 
 # --show-pt-geometry outputs something like
 #     /dev/sda: 164352 cylinders, 4 heads, 32 sectors/track
-sfdisk "${disk}" --show-pt-geometry > "${tmp}" 2>"${err}" &&
-	read _devc cyl _word1 heads _word2 sectors _word3 < "${tmp}" &&
-	CHS="-C $cyl -H $heads -S $sectors" ||
+sfdisk "${disk}" --show-pt-geometry > "${tmp}" 2>"${err}" && \
+	read _devc cyl _word1 heads _word2 sectors _word3 < "${tmp}" && \
+	CHS="-C $cyl -H $heads -S $sectors" || \
 	fail "failed to get CHS from ${disk}"
 
 tot=$((${cyl}*${heads}*${sectors}))
 
 debug 1 "geometry is $CHS. total size=${tot}"
-sfdisk ${CHS} -uS -d "${disk}" > "${dump_out}" 2>"${err}" ||
+sfdisk ${CHS} -uS -d "${disk}" > "${dump_out}" 2>"${err}" || \
 	fail "failed to dump sfdisk info for ${disk}"
 
 {
-echo "## sfdisk ${CHS} -uS -d ${disk}"; 
-cat "${dump_out}"
+	echo "## sfdisk ${CHS} -uS -d ${disk}"
+	cat "${dump_out}"
 }  > "${RESTORE_HUMAN}"
 [ $? -eq 0 ] || fail "failed to save sfdisk -d output"
+
+[ ${VERBOSITY} -gt 0 ] && cat ${RESTORE_HUMAN}
 
 sed -e 's/,//g; s/start=/start /; s/size=/size /' "${dump_out}" > "${dump_mod}"
 
@@ -170,47 +193,49 @@ elif [ "${disk#/dev/loop[0-9]}" != "${disk}" ]; then
 	dpart="${disk}p${part}"
 fi
 
-pt_start=$(awk '$1 == pt { print $4 }' "pt=${dpart}" < "${dump_mod}") &&
-	pt_size=$(awk '$1 == pt { print $6 }' "pt=${dpart}" < "${dump_mod}") &&
-	[ -n "${pt_start}" -a -n "${pt_size}" ] &&
-	pt_end=$((${pt_size}+${pt_start})) ||
-		fail "failed to get start and end for ${dpart} in ${disk}"
+pt_start=$(awk '$1 == pt { print $4 }' "pt=${dpart}" < "${dump_mod}") && \
+	pt_size=$(awk '$1 == pt { print $6 }' "pt=${dpart}" < "${dump_mod}") \
+	&& [ -n "${pt_start}" -a -n "${pt_size}" ] && \
+	pt_end=$((${pt_size}+${pt_start})) || \
+	fail "failed to get start and end for ${dpart} in ${disk}"
 
 # find the minimal starting location that is >= pt_end 
-max_end=$(awk '
-	$3 == "start" { if($4 >= pt_end && $4 < min) { min = $4 } }
+max_end=$(awk '$3 == "start" { if($4 >= pt_end && $4 < min) { min = $4 } } \
 	END { printf("%s\n",min); }' \
-	min=${tot} pt_end=${pt_end} "${dump_mod}") &&
-	[ -n "${max_end}" ] ||
+	min=${tot} pt_end=${pt_end} "${dump_mod}") && \
+	[ -n "${max_end}" ] || \
 	fail "failed to get max_end for partition ${part}"
 
-debug 1 "max_end=${max_end} tot=${tot} pt_end=${pt_end} pt_start=${pt_start} pt_size=${pt_size}"
-[ $((${pt_end})) -eq ${max_end} ] &&
+debug 1 "max_end=${max_end} tot=${tot} pt_end=${pt_end} pt_start=${pt_start}" \
+	"pt_size=${pt_size}"
+[ $((${pt_end})) -eq ${max_end} ] && \
 	nochange "partition ${part} is size ${pt_size}. it cannot be grown"
-[ $((${pt_end}+${fudge})) -gt ${max_end} ] &&
-	nochange "partition ${part} could only be grown by $((${max_end}-${pt_end})) [fudge=${fudge}]"
+[ $((${pt_end}+${fudge})) -gt ${max_end} ] && \
+	nochange "partition ${part} could only be grown by" \
+	"$((${max_end}-${pt_end})) [fudge=${fudge}]"
 
 # now, change the size for this partition in ${dump_out} to be the
 # new size
 new_size=$((${max_end}-${pt_start}))
-sed "\|^\s*${dpart} |s/${pt_size},/${new_size},/" "${dump_out}" > "${new_out}" ||
-	fail "failed to change size in output"
+sed "\|^\s*${dpart} |s/${pt_size},/${new_size},/" "${dump_out}" > \
+	"${new_out}" ||	fail "failed to change size in output"
 
 change_info="partition=${part} start=${pt_start} old: size=${pt_size} end=${pt_end} new: size=${new_size},end=${max_end}"
 if [ $dry_run -ne 0 ]; then
 	echo "CHANGE: ${change_info}"
 	{
-	echo "# === old sfdisk -d ==="
-	cat "${dump_out}"
-	echo "# === new sfdisk -d ==="
-	cat "${new_out}"
+		echo "# === old sfdisk -d ==="
+		cat "${dump_out}"
+		echo "# === new sfdisk -d ==="
+		cat "${new_out}"
 	} 1>&2
 	exit 0
 fi
 
-sfdisk --no-reread "${disk}" ${CHS} --force -O "${orig_bin}" \
-	< "${new_out}" > "${change_out}" 2>&1 || {
-	DISK=${disk}; RESTORE_FROM="${orig_bin}";
+sfdisk --no-reread "${disk}" ${CHS} --force -O "${orig_bin}" < "${new_out}" > \
+	"${change_out}" 2>&1 || {
+	DISK=${disk}
+	RESTORE_FROM="${orig_bin}"
 	error "attempt to resize ${disk} failed. sfdisk output below:"
 	sed 's,^,| ,' "${change_out}" 1>&2
 	fail "failed to resize"
