growpart: fix function styles (no functional changes)
bzr-revno: 208.2.5

diff --git a/bin/growpart b/bin/growpart
--- a/bin/growpart
+++ b/bin/growpart
@@ -1,7 +1,9 @@
 #!/bin/sh
 #    Copyright (C) 2011 Canonical Ltd.
+#    Copyright (C) 2013 Hewlett-Packard Development Company, L.P.
 #
 #    Authors: Scott Moser <smoser@canonical.com>
+#             Juerg Haefliger <juerg.haefliger@hp.com>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -22,10 +24,25 @@ RESTORE_FROM=""
 VERBOSITY=0
 DISK=""
 
-error() { echo "$@" 1>&2; }
-fail() { [ $# -eq 0 ] || echo "FAILED:" "$@"; exit 2; }
-nochange() { echo "NOCHANGE:" "$@"; exit 1; }
-changed() { echo "CHANGED:" "$@"; exit 0; }
+error() {
+	echo "$@" 1>&2
+}
+
+fail() {
+	[ $# -eq 0 ] || echo "FAILED:" "$@"
+	exit 2
+}
+
+nochange() {
+	echo "NOCHANGE:" "$@"
+	exit 1
+}
+
+changed() {
+	echo "CHANGED:" "$@"
+	exit 0
+}
+
 cleanup() {
 	if [ -n "${RESTORE_FROM}" ]; then
 		error "***** WARNING: Resize failed, attempting to revert ******"
@@ -38,11 +55,14 @@ cleanup() {
 	fi
 	[ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
 }
+
 debug() {
-	local level=${1}; shift;
+	local level=${1}
+	shift
 	[ "${level}" -gt "${VERBOSITY}" ] && return
 	error "${@}"
 }
+
 mktemp_d() {
 	# just a mktemp -d that doens't need mktemp if its not there.
 	_RET=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX" 2>/dev/null) && return
@@ -67,14 +87,12 @@ ${0##*/} disk partition
       Resize partition 1 on /dev/sda
 EOF
 }
-bad_Usage() { Usage 1>&2; error "$@"; exit 2; }
 
-#short_opts="hNv"
-#long_opts="help,dry-run,fudge:,verbose"
-#getopt_out=$(getopt --name "${0##*/}" \
-#	--options "${short_opts}" --long "${long_opts}" -- "$@") &&
-#	eval set -- "${getopt_out}" ||
-#	bad_Usage
+bad_Usage() {
+	Usage 1>&2
+	error "$@"
+	exit 2
+}
 
 dry_run=0
 fudge=${FUDGE}
