growpart: capitalize global variable names
bzr-revno: 208.2.7

diff --git a/bin/growpart b/bin/growpart
--- a/bin/growpart
+++ b/bin/growpart
@@ -21,8 +21,11 @@
 FUDGE=${GROWPART_FUDGE:-$((20*1024))}
 TEMP_D=""
 RESTORE_FROM=""
+RESTORE_HUMAN=""
 VERBOSITY=0
 DISK=""
+PART=""
+DRY_RUN=0
 
 error() {
 	echo "$@" 1>&2
@@ -98,10 +101,6 @@ bad_Usage() {
 	exit 2
 }
 
-dry_run=0
-fudge=${FUDGE}
-disk=""
-part=""
 while [ $# -ne 0 ]; do
 	cur=${1}
 	next=${2}
@@ -111,11 +110,11 @@ while [ $# -ne 0 ]; do
 			exit 0
 			;;
 		--fudge)
-			fudge=${next}
+			FUDGE=${next}
 			shift
 			;;
 		-N|--dry-run)
-			dry_run=1
+			DRY_RUN=1
 			;;
 		-v|--verbose)
 			VERBOSITY=$(($VERBOSITY+1))
@@ -128,24 +127,24 @@ while [ $# -ne 0 ]; do
 			fail "unknown option ${cur}"
 			;;
 		*)
-			if [ -z "${disk}" ]; then
-				disk=${cur}
+			if [ -z "${DISK}" ]; then
+				DISK=${cur}
 			else
-				[ -z "${part}" ] || \
+				[ -z "${PART}" ] || \
 					fail "confused by arg ${cur}"
-				part=${cur}
+				PART=${cur}
 			fi
 			;;
 	esac
 	shift
 done
 
-[ -n "${disk}" ] || bad_Usage "must supply disk and partition-number"
-[ -n "${part}" ] || bad_Usage "must supply partition-number"
+[ -n "${DISK}" ] || bad_Usage "must supply disk and partition-number"
+[ -n "${PART}" ] || bad_Usage "must supply partition-number"
 
-[ -e "${disk}" ] || fail "${disk}: does not exist"
+[ -e "${DISK}" ] || fail "${DISK}: does not exist"
 
-[ "${part#*[!0-9]}" = "${part}" ] || fail "partition-number must be a number"
+[ "${PART#*[!0-9]}" = "${PART}" ] || fail "partition-number must be a number"
 
 mktemp_d && TEMP_D="${_RET}" || fail "failed to make temp dir"
 trap cleanup EXIT
@@ -161,19 +160,19 @@ RESTORE_HUMAN="${TEMP_D}/recovery"
 
 # --show-pt-geometry outputs something like
 #     /dev/sda: 164352 cylinders, 4 heads, 32 sectors/track
-sfdisk "${disk}" --show-pt-geometry > "${tmp}" 2>"${err}" && \
+sfdisk "${DISK}" --show-pt-geometry > "${tmp}" 2>"${err}" && \
 	read _devc cyl _word1 heads _word2 sectors _word3 < "${tmp}" && \
 	CHS="-C $cyl -H $heads -S $sectors" || \
-	fail "failed to get CHS from ${disk}"
+	fail "failed to get CHS from ${DISK}"
 
 tot=$((${cyl}*${heads}*${sectors}))
 
 debug 1 "geometry is $CHS. total size=${tot}"
-sfdisk ${CHS} -uS -d "${disk}" > "${dump_out}" 2>"${err}" || \
-	fail "failed to dump sfdisk info for ${disk}"
+sfdisk ${CHS} -uS -d "${DISK}" > "${dump_out}" 2>"${err}" || \
+	fail "failed to dump sfdisk info for ${DISK}"
 
 {
-	echo "## sfdisk ${CHS} -uS -d ${disk}"
+	echo "## sfdisk ${CHS} -uS -d ${DISK}"
 	cat "${dump_out}"
 }  > "${RESTORE_HUMAN}"
 [ $? -eq 0 ] || fail "failed to save sfdisk -d output"
@@ -182,37 +181,37 @@ sfdisk ${CHS} -uS -d "${disk}" > "${dump_out}" 2>"${err}" || \
 
 sed -e 's/,//g; s/start=/start /; s/size=/size /' "${dump_out}" > "${dump_mod}"
 
-dpart="${disk}${part}" # disk and partition number
-if [ -b "${disk}p${part}" -a "${disk%[0-9]}" != "${disk}" ]; then
+dpart="${DISK}${PART}" # disk and partition number
+if [ -b "${DISK}p${PART}" -a "${DISK%[0-9]}" != "${DISK}" ]; then
 	# for block devices that end in a number (/dev/nbd0)
 	# the partition is "<name>p<partition_number>" (/dev/nbd0p1)
-	dpart="${disk}p${part}"
-elif [ "${disk#/dev/loop[0-9]}" != "${disk}" ]; then
+	dpart="${DISK}p${PART}"
+elif [ "${DISK#/dev/loop[0-9]}" != "${DISK}" ]; then
 	# for /dev/loop devices, sfdisk output will be <name>p<number> format
 	# also, even though there is not a device there.
-	dpart="${disk}p${part}"
+	dpart="${DISK}p${PART}"
 fi
 
 pt_start=$(awk '$1 == pt { print $4 }' "pt=${dpart}" < "${dump_mod}") && \
 	pt_size=$(awk '$1 == pt { print $6 }' "pt=${dpart}" < "${dump_mod}") \
 	&& [ -n "${pt_start}" -a -n "${pt_size}" ] && \
 	pt_end=$((${pt_size}+${pt_start})) || \
-	fail "failed to get start and end for ${dpart} in ${disk}"
+	fail "failed to get start and end for ${dpart} in ${DISK}"
 
 # find the minimal starting location that is >= pt_end 
 max_end=$(awk '$3 == "start" { if($4 >= pt_end && $4 < min) { min = $4 } } \
 	END { printf("%s\n",min); }' \
 	min=${tot} pt_end=${pt_end} "${dump_mod}") && \
 	[ -n "${max_end}" ] || \
-	fail "failed to get max_end for partition ${part}"
+	fail "failed to get max_end for partition ${PART}"
 
 debug 1 "max_end=${max_end} tot=${tot} pt_end=${pt_end} pt_start=${pt_start}" \
 	"pt_size=${pt_size}"
 [ $((${pt_end})) -eq ${max_end} ] && \
-	nochange "partition ${part} is size ${pt_size}. it cannot be grown"
-[ $((${pt_end}+${fudge})) -gt ${max_end} ] && \
-	nochange "partition ${part} could only be grown by" \
-	"$((${max_end}-${pt_end})) [fudge=${fudge}]"
+	nochange "partition ${PART} is size ${pt_size}. it cannot be grown"
+[ $((${pt_end}+${FUDGE})) -gt ${max_end} ] && \
+	nochange "partition ${PART} could only be grown by" \
+	"$((${max_end}-${pt_end})) [fudge=${FUDGE}]"
 
 # now, change the size for this partition in ${dump_out} to be the
 # new size
@@ -220,8 +219,8 @@ new_size=$((${max_end}-${pt_start}))
 sed "\|^\s*${dpart} |s/${pt_size},/${new_size},/" "${dump_out}" > \
 	"${new_out}" ||	fail "failed to change size in output"
 
-change_info="partition=${part} start=${pt_start} old: size=${pt_size} end=${pt_end} new: size=${new_size},end=${max_end}"
-if [ $dry_run -ne 0 ]; then
+change_info="partition=${PART} start=${pt_start} old: size=${pt_size} end=${pt_end} new: size=${new_size},end=${max_end}"
+if [ ${DRY_RUN} -ne 0 ]; then
 	echo "CHANGE: ${change_info}"
 	{
 		echo "# === old sfdisk -d ==="
@@ -232,11 +231,10 @@ if [ $dry_run -ne 0 ]; then
 	exit 0
 fi
 
-sfdisk --no-reread "${disk}" ${CHS} --force -O "${orig_bin}" < "${new_out}" > \
+sfdisk --no-reread "${DISK}" ${CHS} --force -O "${orig_bin}" < "${new_out}" > \
 	"${change_out}" 2>&1 || {
-	DISK=${disk}
 	RESTORE_FROM="${orig_bin}"
-	error "attempt to resize ${disk} failed. sfdisk output below:"
+	error "attempt to resize ${DISK} failed. sfdisk output below:"
 	sed 's,^,| ,' "${change_out}" 1>&2
 	fail "failed to resize"
 }
