More busybox compatibility changes
Changes:
 * Use short flags for BusyBox compatibility when needed.
 * test-growpart(-lvm): run `udevadm settle` only if available.
 * Drop `rm --one-file-system` flag in mount-image-callback's cleanup().
   We check for the return code of do_umounts() instead, and avoid
   removing files if something went wrong in the umount process.

diff --git a/bin/mount-image-callback b/bin/mount-image-callback
--- a/bin/mount-image-callback
+++ b/bin/mount-image-callback
@@ -120,12 +120,11 @@ do_umounts() {
 cleanup() {
 	if [ "${#UMOUNTS[@]}" -ne 0 ]; then
 		debug 2 "umounts: ${UMOUNTS[*]}"
-		do_umounts "${UMOUNTS[@]}"
+		do_umounts "${UMOUNTS[@]}" ||
+			{ error "failed cleaning up mounts"; return 1; }
 	fi
 	disconnect_qemu
-	[ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] ||
-		rm --one-file-system -Rf "${TEMP_D}" ||
-		error "removal of temp dir failed!"
+	rm -Rf "$TEMP_D" || error "removal of temp dir failed!"
 }
 
 debug() {
