growpart: correct some overprovisioning logic
Correct some of the overprovisioning logic.

Change overprovisioning testcase to not require root.

Also correct some off-by-one errors in the existing growpart code and
correct some existing testcases affected by this.

diff --git a/test/test-growpart-overprovision b/test/test-growpart-overprovision
--- a/test/test-growpart-overprovision
+++ b/test/test-growpart-overprovision
@@ -1,40 +1,17 @@
 #!/bin/bash
-# NEED_ROOT
+#
+# Just create an image in the filesystem, then grow it.
 
 set -e
-
-[ "$(id -u)" = "0" ] ||
-	{ echo "sorry, must be root"; exit 1; }
 
 PT_TYPE="${PT_TYPE:-dos}" # dos or gpt
 size=${DISK_SIZE_NEW:-100M}
 osize=${DISK_SIZE_ORIG:-50M}
 freepercent=${OVER_PROVISION_PERCENT:-10}
 
-LODEV=""
 TEMP_D=""
 
-clearparts() {
-	# read /proc/partitions, clearing any partitions on dev (/dev/loopX)
-	local dev="$1"
-	local short=${dev##*/} parts="" part=""
-	parts=$(awk '$4 ~ m { sub(m,"",$4); print $4 }' \
-		"m=${short}p" /proc/partitions)
-	[ -z "$parts" ] && return
-	echo "clearing parts [$parts] from $dev"
-	for part in $parts; do
-		echo "delpart $LODEV $part"
-		delpart $LODEV $part
-	done
-	udevadm settle
-}
 cleanup() {
-	if [ -n "$LODEV" ]; then
-		clearparts "$LODEV"
-		echo "losetup --detach $LODEV";
-		losetup --detach "$LODEV";
-		udevadm settle
-	fi
 	[ ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
 }
 rq() {
@@ -58,48 +35,34 @@ echo "2048," | rq sfdisk $label_flag --force --unit=S "$img"
 
 truncate --size "$size" "$img"
 
-lodev=$(losetup --show --find "$img")
-LODEV=$lodev
-echo "set up $lodev"
-
-# clear any old ones that might be around (LP: #1136781)
-clearparts "$lodev"
-partx --add $lodev
-lodevpart="${lodev}p1"
-
 echo "==== before ===="
-grep "${lodev##*/}" /proc/partitions
-sfdisk --list --unit=S "$lodev"
+sfdisk --list --unit=S "$img"
 
-errfile="${TEMP_D}/growpart.err"
-growpart -v -v --free-percent "$freepercent" "$lodev" 1 2>"$errfile" || {
-	rc=$?
-	echo "failed [$rc]: growpart -v -v --free-percent $freepercent $lodev 1"
-	cat "$errfile" 1>&2
-	exit $rc
-}
-
-out=$(grep "FLOCK:.*releasing exclusive lock" "$errfile") || :
-if [ -z "$out" ]; then
-	echo "ERROR: growpart stderr did not mention releasing lock"
+err="${TEMP_D}/gp.err"
+out="${TEMP_D}/gp.out"
+if ! growpart -v -v --free-percent "$freepercent" "$img" 1 2>"$err" > "$out"; then
+	cat "$err" "$out"
+	echo "failed"
 	exit 1
 fi
-
-echo === growpart stderr ===
-cat "$errfile"
+echo "==== growpart-stderr ===="
+cat "$err"
+echo "==== growpart-stdout ===="
+cat "$out"
+grep -q "^CHANGED:" "$out" ||
+	{ echo "did not find 'CHANGED'"; exit 1; }
 
 echo "==== after ===="
-grep "${lodev##*/}" /proc/partitions
-sfdisk --list --unit=S "$lodev"
+sfdisk --list --unit=S "$img"
 
-enddevice=$(grep "${lodev##*/}" /proc/partitions|grep -v "${lodevpart##*/}"|awk '{print $3}')
-endpart=$(grep "${lodevpart##*/}" /proc/partitions|awk '{print $3}')
-# Subtract the following from disk image end:
-#   - required percentage of overprovisioning
-#   - 1024 MiB (the partition start, 2048 sectors of 512 bytes)
-#   - 17 MiB (rounded up value of MBR padding of 33 sectors for GPT conversion)
-# to calculate the expected end of resized partition.
-expectedendpart=$((enddevice-(enddevice/100*freepercent)-1024-17))
+enddevice=$(sfdisk --list --unit=S "$img" | grep "Disk $img:" | awk '{print $7}')
+endpart=$(sfdisk --list --unit=S "$img" | grep "$img" | grep -v "Disk" | awk '{print $3}')
+# Subtract the following from disk image end in sectors:
+#   - required number of overprovisioning sectors to leave unused
+#   - 33 sectors (MBR padding for GPT conversion)
+#   - 1 (as sector numbers start from 0)
+# to calculate the expected end of resized partition in sectors.
+expectedendpart=$((enddevice-(enddevice/100*freepercent)-33-1))
 echo
 if [ $endpart = $expectedendpart ]; then
 	echo "Final partition size matches expected partition size"
