modify growpart to take disk and partition as 2 params.
bzr-revno: 93

diff --git a/growpart b/growpart
--- a/growpart
+++ b/growpart
@@ -20,6 +20,7 @@ FUDGE=${GROWPART_FUDGE:-$((20*1024))}
 TEMP_D=""
 RESTORE_FROM=""
 VERBOSITY=0
+DISK=""
 
 error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || echo "FAILED:" "$@"; exit 1; }
@@ -28,7 +29,7 @@ changed() { echo "CHANGED:" "$@"; exit 0; }
 cleanup() {
 	if [ -n "${RESTORE_FROM}" ]; then
 		error "***** WARNING: Resize failed, attempting to revert ******"
-		if sfdisk "${ROOTDISK}" ${CHS} -I "${RESTORE_FROM}"; then
+		if sfdisk "${DISK}" ${CHS} -I "${RESTORE_FROM}"; then
 			error "***** Appears to have gone OK ****"
 		else
 			error "***** FAILED! or original partition table looked like: ****"
@@ -62,6 +63,7 @@ ${0##*/} partition
     -v | --verbose   increase verbosity / debug
 EOF
 }
+bad_Usage() { Usage 1>&2; error "$@"; exit 1; }
 
 #short_opts="hNv"
 #long_opts="help,dry-run,fudge:,verbose"
@@ -72,7 +74,8 @@ EOF
 
 dry_run=0
 fudge=${FUDGE}
-part_in=""
+disk=""
+part=""
 while [ $# -ne 0 ]; do
 	cur=${1}; next=${2};
 	case "$cur" in
@@ -81,27 +84,25 @@ while [ $# -ne 0 ]; do
 		   --dry-run) dry_run=1;;
 		-v|--verbose) VERBOSITY=$(($VERBOSITY+1));;
 		--) shift; break;;
-        -*) fail "confused by arg ${cur}";;
-		*) [ -z "${part_in}" ] || fail "confused by arg ${part_in}"
-			part_in=${cur};;
+        -*) fail "unknown option ${cur}";;
+		*) 
+			if [ -z "${disk}" ]; then
+				disk=${cur};
+			else
+				[ -z "${part}" ] || fail "confused by arg ${cur}"
+				part=${cur};
+			fi
+			;;
 	esac
 	shift;
 done
 
-[ -n "${part_in}" ] || { Usage 1>&2; exit 1; }
+[ -n "${disk}" ] || bad_Usage "must supply disk and partition-number"
+[ -n "${part}" ] || bad_Usage "must supply partition-number"
 
-{ [ ! -L "${part}" ] && part=${part_in} || r=$(readlink -f "${part}") ; } ||
-	fail "failed to get full path for ${part_in}"
+[ -e "${disk}" ] || { fail "${disk}: does not exist"; }
 
-case "${part}" in
-	*[0-9])
-		rootdisk=${part%%[0-9]*}
-		pnum=${part#${rootdisk}}
-		;;
-	# the root is a disk, not a partition, no need to do anything
-	# in this case, the kernel already knows the full size.
-	*) fail "${part_in} is not a partition";;
-esac
+[ "${part#*[^0-9]}" != "${part}" ] || fail "partition-number must be a number"
 
 mktemp_d && TEMP_D="${_RET}" || fail "failed to make temp dir"
 trap cleanup EXIT
@@ -118,30 +119,31 @@ RESTORE_HUMAN="${TEMP_D}/recovery"
 
 # --show-pt-geometry outputs something like
 #     /dev/sda: 164352 cylinders, 4 heads, 32 sectors/track
-sfdisk "${rootdisk}" --show-pt-geometry > "${tmp}" 2>"${err}" &&
+sfdisk "${disk}" --show-pt-geometry > "${tmp}" 2>"${err}" &&
 	read _devc cyl _word1 heads _word2 sectors _word3 < "${tmp}" &&
 	CHS="-C $cyl -H $heads -S $sectors" ||
-	fail "failed to get CHS from ${rootdisk}"
+	fail "failed to get CHS from ${disk}"
 
 tot=$((${cyl}*${heads}*${sectors}))
 
 debug 1 "geometry is $CHS. total size=${tot}"
-sfdisk ${CHS} -uS -d "${rootdisk}" > "${dump_out}" 2>"${err}" ||
-	fail "failed to dump sfdisk info for ${rootdisk}"
+sfdisk ${CHS} -uS -d "${disk}" > "${dump_out}" 2>"${err}" ||
+	fail "failed to dump sfdisk info for ${isk}"
 
 {
-echo "## sfdisk ${CHS} -uS -d ${rootdisk}"; 
+echo "## sfdisk ${CHS} -uS -d ${disk}"; 
 cat "${dump_out}"
 }  > "${RESTORE_HUMAN}"
 [ $? -eq 0 ] || fail "failed to save sfdisk -d output"
 
 sed -e 's/,//g; s/start=/start /; s/size=/size /' "${dump_out}" > "${dump_mod}"
 
-pt_start=$(awk '$1 == pt { print $4 }' "pt=${part}" < "${dump_mod}") &&
-	pt_size=$(awk '$1 == pt { print $6 }' "pt=${part}" < "${dump_mod}") &&
+dpart="${disk}${part}" # disk and partition number
+pt_start=$(awk '$1 == pt { print $4 }' "pt=${dpart}" < "${dump_mod}") &&
+	pt_size=$(awk '$1 == pt { print $6 }' "pt=${dpart}" < "${dump_mod}") &&
 	[ -n "${pt_start}" -a -n "${pt_size}" ] &&
 	pt_end=$((${pt_size}+${pt_start})) ||
-		fail "failed to get start and end for ${part}"
+		fail "failed to get start and end for ${dpart} in ${disk}"
 
 # find the minimal starting location that is >= pt_end 
 max_end=$(awk '
@@ -149,21 +151,21 @@ max_end=$(awk '
 	END { printf("%s\n",min); }' \
 	min=${tot} pt_end=${pt_end} "${dump_mod}") &&
 	[ -n "${max_end}" ] ||
-	fail "failed to get max_end for ${part}"
+	fail "failed to get max_end for partition ${part}"
 
 debug 1 "max_end=${max_end} tot=${tot} pt_end=${pt_end} pt_start=${pt_start} pt_size=${pt_size}"
 [ $((${pt_end})) -eq ${max_end} ] &&
-    nochange "${part} is size ${pt_size}. it cannot be grown"
+    nochange "partition ${part} is size ${pt_size}. it cannot be grown"
 [ $((${pt_end}+${fudge})) -gt ${max_end} ] &&
-	nochange "${part} could only be grown by $((${max_end}-${pt_end})) [fudge=${fudge}]"
+	nochange "partition ${part} could only be grown by $((${max_end}-${pt_end})) [fudge=${fudge}]"
 
 # now, change the size for this partition in ${dump_out} to be the
 # new size
 new_size=$((${max_end}-${pt_start}))
-sed "\|^${part} |s/${pt_size},/${new_size},/" "${dump_out}" > "${new_out}" ||
+sed "\|^${dpart} |s/${pt_size},/${new_size},/" "${dump_out}" > "${new_out}" ||
 	fail "failed to change size in output"
 
-change_info="${part} start=${pt_start} old: size=${pt_size} end=${pt_end} new: size=${new_size},end=${max_end}"
+change_info="partition=${part} start=${pt_start} old: size=${pt_size} end=${pt_end} new: size=${new_size},end=${max_end}"
 if [ $dry_run -ne 0 ]; then
     echo "CHANGE: ${change_info}"
 	{
@@ -175,9 +177,9 @@ if [ $dry_run -ne 0 ]; then
     exit 0
 fi
 
-sfdisk "${rootdisk}" ${CHS} --force -O "${orig_bin}" \
+sfdisk "${disk}" ${CHS} --force -O "${orig_bin}" \
 	< "${new_out}" > "${change_out}" 2> "${change_err}" || {
-	ROOTDISK=${rootdisk}; RESTORE_FROM="${orig_bin}";
+	DISK=${disk}; RESTORE_FROM="${orig_bin}";
 	fail "failed to resize"
 }
 changed "${change_info}"
