ssh-import-lp-id: ensure that $HOME is set properly, LP: #528029; add a usage statement
LP: #528029
bzr-revno: 10.1.3

diff --git a/ssh-import-lp-id b/ssh-import-lp-id
--- a/ssh-import-lp-id
+++ b/ssh-import-lp-id
@@ -22,6 +22,16 @@
 # Abort on any unhandled error
 set -e
 
+usage() {
+	echo
+	echo "Usage:"
+	echo "  $0 [Launchpad_ID_1] [Launchpad_ID_2] ... [Launchpad_ID_n]"
+	echo
+	exit 1
+}
+
+[ -n "$1" ] || usage
+
 error() {
 	printf "ERROR: %s\n" "$@" 1>&2
 	exit 1
@@ -55,11 +65,20 @@ validate_keys() {
 URL="https://launchpad.net/~%s/+sshkeys"
 
 # Only support writing to this user's authorized_keys file
+if [ -z "$HOME" ]; then
+	uid=$(id -u) || error "Cannot determine user id"
+	[ -n "$uid" ] || error "User id cannot be empty"
+	pwline=$(getent passwd "$uid") || error "Cannot get passwd entry"
+	HOME=$(echo "$pwline" | awk -F: '{print $6}') || error "Cannot determine home directory"
+	[ -n "$HOME" ] || error "Home directory cannot be empty"
+fi
+
 DIR="$HOME/.ssh"
 FILE="$DIR"/authorized_keys
 
 mkdir -m 0700 "$DIR" 2>/dev/null || true
 [ -d "$DIR" ] || error "Cannot create directory [$DIR]"
+[ -w "$DIR" ] || error "Cannot write to directory [$DIR]"
 
 rc=0
 tmp=$(mktemp)
