[ Scott Moser ] * ssh-import-lp-id: allow dss keys * uec-publish-tarball: add -q/--quiet flag * uec-publish-image:   - remove trailing slash on bucket input which caused failed register   - remove trailing tab in output   - on error, make sure user sees command output   - add -B/--device-block-mapping pass through to euca-bundle-image * uec-resize-image: make quiet by default, add --verbose,-v * uec-query-builds: support querying 'latest-ec2'
[ Dustin Kirkland ]
* debian/install, debian/manpages, uec-run-instances,
  uec-run-instances.1: add a wrapper for euca-run-instances that
  can easily/cleanly inject ssh keys from Launchpad.net, LP: #524101

LP: #524101
Original authors:
  - Dustin Kirkland <kirkland@ubuntu.com>
  - Scott Moser
  - Dustin Kirkland
bzr-revno: 10.1.6

diff --git a/uec-publish-tarball b/uec-publish-tarball
--- a/uec-publish-tarball
+++ b/uec-publish-tarball
@@ -21,12 +21,18 @@
 
 
 TMPD=""
+VERBOSITY=1
 error() { echo "$@" 1>&2; }
-log() { error "$(date): ====== $1 ======" ; }
+debug() { 
+	[ ${VERBOSITY} -ge $1 ] || return 0; 
+	shift
+	error "$@"
+}
+log() { debug "$1" "$(date): ====== $2 ======" ; }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 cleanup() {
 	[ -n "${TMPD}" -a -d "${TMPD}" ] || return 0;
-	echo "cleaning up ${TMPD}"
+	debug 2 "cleaning up ${TMPD}"
 	rm -Rf "${TMPD}";
 }
 bad_Usage() { Usage 1>&2; [ $# -eq 0 ] || error "$@"; exit 1; }
@@ -47,7 +53,7 @@ Usage: ${0##*/} [ options ] tarfile bucket [arch]
 
            --resize  s        resize the image to 's' bundling uploading
                               's' must be valid input to uec-resize-image
-
+      -q | --quiet            be quiet, only output published ids
 
    Example:
    - ${0##*/} lucid-uec-i386.tar.gz my-lucid-bucket i386
@@ -62,8 +68,8 @@ upload_register() {
 }
 
 
-short_opts="hk:K:r:R:"
-long_opts="help,kernel:,kernel-file:,ramdisk:,ramdisk-file:,resize:"
+short_opts="hk:K:qr:R:"
+long_opts="help,kernel:,kernel-file:,quiet,ramdisk:,ramdisk-file:,resize:"
 getopt_out=$(getopt --name "${0##*/}" --shell sh \
 	--options "${short_opts}" --long "${long_opts}" -- "$@") &&
 	eval set -- "${getopt_out}" ||
@@ -87,6 +93,7 @@ while [ $# -ne 0 ]; do
 			[ -f "${next}" ] && kernel=$(readlink -f "${next}") ||
 				fail "failed to get path to ${next}"
 			shift;;
+		-q|--quiet) VERBOSITY=0;;
 		-r|--ramdisk) eri=${next}; shift;;
 		-R|--ramdisk-file)
 			[ -f "${next}" ] && ramdisk=$(readlink -f "${next}") ||
@@ -128,7 +135,7 @@ start=$PWD
 
 cd "${TMPD}"
 
-log "extracting image"
+log 1 "extracting image"
 tar -S -xzf "${tbf}" || fail "failed extract ${tarball}"
 
 for x in *; do
@@ -145,39 +152,41 @@ done
 [ -n "${kernel}" -o -n "${eki}" ] ||
 	bad_Usage "can't find kernel. specify '--kernel none' to register none";
 [ -n "${ramdisk}" -o -n "${eri}" ] || {
-	error "Warning: no ramdisk found, assuming '--ramdisk none'"
+	debug 1 "Warning: no ramdisk found, assuming '--ramdisk none'"
 	eri="none";
 }
 
-error "kernel : ${eki:-${kernel}}"
-error "ramdisk: ${eri:-${ramdisk}}"
-error "image  : ${image##*/}"
+debug 1 "kernel : ${eki:-${kernel}}"
+debug 1 "ramdisk: ${eri:-${ramdisk}}"
+debug 1 "image  : ${image##*/}"
 
 if [ -n "${resize}" ]; then
-	log "resizing ${image##*/} to ${resize}"
-	uec-resize-image "${image}" "${resize}" ||
-		fail "failed to resize image file to ${resize}"
+	log 1 "resizing ${image##*/} to ${resize}"
+	out=$(uec-resize-image "${image}" "${resize}" 2>&1) || {
+		error "${out}";
+		fail "failed to resize image file to ${resize}";
+	}
 fi
 
 if [ -n "${kernel}" ]; then
-	log "bundle/upload kernel"
+	log 1 "bundle/upload kernel"
 	upload_register --type kernel "${iarch}" "${kernel}" "${bucket}" ||
 		fail "failed to upload kernel"
 	eki=${_RET}
 fi
 
 if [ -n "${ramdisk}" ]; then
-	log "bundle/upload ramdisk"
+	log 1 "bundle/upload ramdisk"
 	upload_register --type ramdisk "${iarch}" "${ramdisk}" "${bucket}" ||
 		fail "failed ramdisk bundle/upload"
 	eri=${_RET}
 fi
 
-log "bundle/upload image"
+log 1 "bundle/upload image"
 upload_register --type image "${iarch}" "${image}" "${bucket}" \
 	--kernel "${eki}" --ramdisk "${eri}" ||
 		fail "failed bundle/upload/register of image"
 emi=${_RET}
 
-log "done"
+log 1 "done"
 printf 'emi="%s"; eri="%s"; eki="%s";\n' "${emi}" "${eri}" "${eki}"
diff --git a/uec-resize-image b/uec-resize-image
--- a/uec-resize-image
+++ b/uec-resize-image
@@ -21,11 +21,14 @@
 
 Usage() {
 	cat <<EOF
-Usage: ${0##*/} image size [output]
+Usage: ${0##*/} [ options ] image size [output]
    Resize a UEC image to a new size.
    if output is given, do not modify 'image', but create new file 'output'
 
    New size is specified per resize2fs(8), e.g. "1G" for 1 gigabyte
+
+   options:
+      -v | --verbose    show command output
 EOF
 	return 0
 }
@@ -61,7 +64,22 @@ xtruncate() {
    fi
 }
 
+runcmd() {
+   local output=$1
+   shift;
+   if [ "$output" = "0" ]; then
+      local out="" ret=0;
+      out=$("${@}" 2>&1) || { ret=$?; error "${out}"; return $ret; }
+   else
+      "$@"
+   fi
+}
+
 [ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }
+
+verbose=0
+[ "$1" = "-v" -o "$1" = "--verbose" ] &&
+   { verbose=1; shift; }
 
 [ $# -eq 3 -o $# -eq 2 ] || { Usage 1>&2; exit 1; }
 
@@ -109,16 +127,20 @@ ls_out=$(ls -l "${new}") &&
    old_size=$(echo "${ls_out}" | awk '{print $5}') ||
    fail "failed to get size of ${new_img}"
 
-e2fsck -fp "$new" || fail "failed to fsck ${new}"
+runcmd "${verbose}" e2fsck -fp "${new}" ||
+   fail "failed to fsck ${new}"
 
 if [ "${old_size}" -lt "${new_size}" ]; then
    xtruncate "--size=$size" "$new" || fail "failed to change size of ${new}"
 fi
 
-resize2fs "$new" "$size" || fail "failed to resize ${new} -> ${size}"
+runcmd "${verbose}" resize2fs "$new" "$size" ||
+   fail "failed to resize ${new} -> ${size}"
 
 if [ "${old_size}" -gt "${new_size}" ]; then
    xtruncate "--size=$size" "$new" || fail "failed to change size of ${new}"
 fi
+
+echo "resized ${new} to ${size}"
 
 exit 0
